services:
#  api:
#    build: ./api
#    container_name: images-api
#    hostname: api
#    env_file:
#      - ./api/.env
#    ports:
#      - 8080:8080
#    depends_on:
##      - minio
#      - nats
#      - postgres
#      - worker
#  worker:
#    build: ./worker
#    container_name: images-worker
#    hostname: worker
#    env_file:
#      - ./worker/.env
#    ports:
#      - 8081:8081
#    depends_on:
##      - minio
#      - nats
#      - postgres
#  minio:
#    image: minio/minio
#    container_name: images-minio
#    hostname: storage
#    entrypoint: server /data --console-address :9001
#    env_file:
#      - .env
#    ports:
#      - 9000:9000
#      - 9001:9001
#    restart: always
#    volumes:
#      - ./data/storage:/data
  nats:
    image: nats:latest
    container_name: images-nats
    hostname: nats
    env_file:
      - .env
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    restart: always
  postgres:
    image: postgres:15.0-alpine
    container_name: images-postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
