FROM gradle:8.4.0-jdk21 as builder
WORKDIR /app
COPY --chown=gradle:gradle . /app
RUN gradle clean build -x test --no-daemon -p worker

FROM amazoncorretto:21
EXPOSE 8081
RUN mkdir /app
COPY --from=builder /app/worker/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
