FROM gradle:8.4.0-jdk21 as builder
WORKDIR /app
COPY --chown=gradle:gradle . /app
RUN gradle clean build -x test --no-daemon -p api

FROM amazoncorretto:21
EXPOSE 8080
RUN mkdir /app
COPY --from=builder /app/api/build/libs/*.jar /app/app.jar
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.1/opentelemetry-javaagent.jar /opt/opentelemetry-agent.jar
ENTRYPOINT ["java", "-javaagent:/opt/opentelemetry-agent.jar", "-Dotel.resource.attributes=service.instance.id=$HOSTNAME", "-jar", "/app/app.jar"]
