### Health
GET {{base_url}}/health

### Users
GET {{base_url}}/api/users

### Images
GET {{base_url}}/api/images

### Download image
@image_id = fc6e7f1b-34c0-481c-9fb3-8ada55b49bc6
GET {{base_url}}/api/images/{{image_id}}/download

### Accepted mime types
GET {{base_url}}/api/images/accepted

### Image Operations
GET {{base_url}}/api/operations

### Upload valid image
POST {{base_url}}/api/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1-2016x1512-360k.jpg"

< ./etc/test-images/test1-2016x1512-360k.jpg
--WebAppBoundary--

### Upload invalid image


### Upload a non-image file

