### Health
GET {{base_url}}/actuator/health

### Login
POST {{base_url}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Who am I?
GET {{base_url}}/whoami
Authorization: Bearer {{auth_token}}

### Images
GET {{base_url}}/api/images
Authorization: Bearer {{auth_token}}

### Logs
GET {{base_url}}/api/logs
Authorization: Bearer {{auth_token}}

### Accepted mime types
GET {{base_url}}/api/images/accepted-mime-types

### Image Operations
GET {{base_url}}/api/operations

### Upload valid image
POST {{base_url}}/api/images/upload
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1-2016x1512-360k.jpg"

< ./etc/test-images/test1-2016x1512-360k.jpg
--WebAppBoundary--

> {% client.global.set("image_id", response.body.id); %}

### Image by id
#@image_id = a96c3347-d804-4d86-bfb9-ba87a8e8038b
GET {{base_url}}/api/images/{{image_id}}
Authorization: Bearer {{auth_token}}

### Download image
#@image_id = 92099701-604a-4048-9325-107bf44dc463
GET {{base_url}}/api/images/{{image_id}}/download
Authorization: Bearer {{auth_token}}

### Upload invalid image
POST {{base_url}}/api/images/upload
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="brain-1552824775.svg"

< ./etc/test-images/brain-1552824775.svg

### Upload a non-image file

